from __future__ import annotations

from pathlib import Path

from sqlalchemy import create_engine, event
from sqlalchemy.ext.asyncio import AsyncEngine, async_sessionmaker, create_async_engine

from .models import Base


def upgrade_database(database_url: str) -> None:
    """Bring the database up to `models.py`, which is the only schema source.

    Safwa is pre-release and has no migration history: the owner recreates the database
    instead of migrating it, so the schema is created straight from the metadata rather
    than replayed from Alembic revisions.  `create_all` adds missing tables and indexes
    and never alters an existing one, so a changed column still needs a rebuilt
    `data/safwa.db` (back it up first with `uv run safwa-backup`).  Add Alembic back with
    an autogenerated baseline when the schema has to survive a release.
    """
    if database_url.startswith("sqlite:///"):
        Path(database_url.removeprefix("sqlite:/// ".strip())).parent.mkdir(
            parents=True, exist_ok=True
        )
    engine = create_engine(database_url)
    try:
        Base.metadata.create_all(engine)
    finally:
        engine.dispose()


class Database:
    def __init__(self, url: str) -> None:
        self.engine: AsyncEngine = create_async_engine(url, pool_pre_ping=True)
        self.sessions = async_sessionmaker(self.engine, expire_on_commit=False)

        @event.listens_for(self.engine.sync_engine, "connect")
        def configure_sqlite(connection, _record) -> None:  # type: ignore[no-untyped-def]
            cursor = connection.cursor()
            cursor.execute("PRAGMA foreign_keys=ON")
            cursor.execute("PRAGMA journal_mode=WAL")
            cursor.execute("PRAGMA busy_timeout=5000")
            cursor.close()

    async def dispose(self) -> None:
        await self.engine.dispose()
