"""Classify the existing tests by the taxonomy in the plan, section 18.5.

The class here is *provisional*: it is read off mechanical signals, not off the behaviour a
test asserts.  The final class is decided at gate A of the feature that owns the test, and
that decision is what the audit table records.  This script exists so that gate starts from
a list instead of from a directory.

    uv run python scripts/test_inventory.py            # write docs/brd/test_inventory.md
    uv run python scripts/test_inventory.py --tests    # print every test with its signals
"""

from __future__ import annotations

import ast
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TESTS = REPO / "tests"
OUTPUT = REPO / "docs" / "brd" / "test_inventory.md"

FAKES = ("Mock", "AsyncMock", "MagicMock", "monkeypatch", "patch")
UI_WORDS = ("keyboard", "inline_keyboard", "reply_markup", "buttons", "callback_data", "markup")
# Files whose subject is a technical contract rather than a business outcome.
CONTRACT_FILES = (
    "test_infrastructure.py",
    "test_provider.py",
    "test_config.py",
    "test_qa.py",
    "test_backup.py",
    "test_ai_sql.py",
    "test_asr.py",
    "test_architecture.py",
    "test_state_flow.py",
)


@dataclass(frozen=True, slots=True)
class TestCase:
    file: str
    name: str
    line: int
    signals: tuple[str, ...]

    @property
    def provisional_class(self) -> str:
        if "private-import" in self.signals or "ui-layout" in self.signals:
            return "implementation_coupled"
        if "contract-file" in self.signals:
            return "characterization_valid"
        return "business_valid"


def _private_names(tree: ast.Module) -> set[str]:
    """Underscore names the file borrows from `safwa`, so the signal can be per test.

    The import is the file's; only the tests that actually name one are coupled to it.
    """
    names = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and (node.module or "").startswith("safwa"):
            names |= {alias.asname or alias.name for alias in node.names if alias.name.startswith("_")}
    return names


def _source_of(node: ast.AST, lines: list[str]) -> str:
    end = getattr(node, "end_lineno", node.lineno)
    return "\n".join(lines[node.lineno - 1 : end])


def collect() -> list[TestCase]:
    cases: list[TestCase] = []
    for path in sorted(TESTS.rglob("test_*.py")):
        if "__pycache__" in path.parts:
            continue
        text = path.read_text(encoding="utf-8-sig")
        lines = text.splitlines()
        tree = ast.parse(text, str(path))
        rel = path.relative_to(TESTS).as_posix()
        private = _private_names(tree)
        file_signals = ["contract-file"] if path.name in CONTRACT_FILES else []
        for node in ast.walk(tree):
            if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
                continue
            if not node.name.startswith("test_"):
                continue
            body = _source_of(node, lines)
            signals = list(file_signals)
            if any(name in body for name in private):
                signals.append("private-import")
            if any(word in body for word in FAKES):
                signals.append("fakes")
            if any(word in body for word in UI_WORDS):
                signals.append("ui-layout")
            if "# Given" in body or "# When" in body or "# Then" in body:
                signals.append("given-when-then")
            cases.append(TestCase(rel, node.name, node.lineno, tuple(sorted(set(signals)))))
    return cases


CLASSES = ("business_valid", "characterization_valid", "implementation_coupled")


def render(cases: list[TestCase]) -> str:
    by_file: dict[str, list[TestCase]] = {}
    for case in cases:
        by_file.setdefault(case.file, []).append(case)

    rows = ["| File | Tests | business | characterization | impl-coupled | Signals |", "|---|---:|---:|---:|---:|---|"]
    for name in sorted(by_file):
        group = by_file[name]
        counts = Counter(case.provisional_class for case in group)
        signals = sorted({signal for case in group for signal in case.signals})
        rows.append(
            f"| `{name}` | {len(group)} | {counts['business_valid']} | "
            f"{counts['characterization_valid']} | {counts['implementation_coupled']} | "
            f"{', '.join(signals) or '—'} |"
        )
    totals = Counter(case.provisional_class for case in cases)
    rows.append(
        f"| **total** | **{len(cases)}** | **{totals['business_valid']}** | "
        f"**{totals['characterization_valid']}** | **{totals['implementation_coupled']}** | |"
    )

    return "\n".join(
        [
            "# Test inventory",
            "",
            "Generated by `scripts/test_inventory.py`. Counts are test *functions*; parametrised",
            "cases collect as more.",
            "",
            "The class in this table is **provisional** — it comes from mechanical signals, not from",
            "reading what the test asserts. The binding class is decided at gate A of the feature that",
            "owns the test and recorded in that batch's audit table. `contradictory`, `obsolete` and",
            "`missing` cannot be detected mechanically and appear only there.",
            "",
            "Signals: `private-import` — the file imports an underscore name from `safwa`;",
            "`ui-layout` — the body mentions keyboards, markup or callback data; `fakes` — the body",
            "uses `Mock`, `AsyncMock`, `patch` or `monkeypatch`; `contract-file` — the file's subject is",
            "a technical contract; `given-when-then` — the body already carries the comment markers.",
            "",
            *rows,
            "",
        ]
    )


def main() -> None:
    cases = collect()
    if "--tests" in sys.argv:
        for case in cases:
            print(f"{case.provisional_class:<24} {case.file}:{case.line} {case.name} {list(case.signals)}")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(cases), encoding="utf-8")
    print(f"{len(cases)} tests -> {OUTPUT.relative_to(REPO).as_posix()}")


if __name__ == "__main__":
    main()
